# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ndata.proto\"i\n\x07Message\x12\x12\n\ngeneration\x18\x01 \x01(\x05\x12\x0f\n\x07\x66itness\x18\x02 \x01(\x02\x12\x18\n\x10normalizeFitness\x18\x03 \x01(\x02\x12\x0f\n\x07weights\x18\x04 \x03(\x05\x12\x0e\n\x06\x64\x65lays\x18\x05 \x03(\x02\"\x1d\n\x0bServerReply\x12\x0e\n\x06status\x18\x01 \x01(\x05\x32K\n\x16\x42idirectionalStreaming\x12\x31\n\x11GetServerResponse\x12\x08.Message\x1a\x0c.ServerReply\"\x00(\x01\x30\x01\x62\x06proto3')



_MESSAGE = DESCRIPTOR.message_types_by_name['Message']
_SERVERREPLY = DESCRIPTOR.message_types_by_name['ServerReply']
Message = _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGE,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:Message)
  })
_sym_db.RegisterMessage(Message)

ServerReply = _reflection.GeneratedProtocolMessageType('ServerReply', (_message.Message,), {
  'DESCRIPTOR' : _SERVERREPLY,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:ServerReply)
  })
_sym_db.RegisterMessage(ServerReply)

_BIDIRECTIONALSTREAMING = DESCRIPTOR.services_by_name['BidirectionalStreaming']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MESSAGE._serialized_start=14
  _MESSAGE._serialized_end=119
  _SERVERREPLY._serialized_start=121
  _SERVERREPLY._serialized_end=150
  _BIDIRECTIONALSTREAMING._serialized_start=152
  _BIDIRECTIONALSTREAMING._serialized_end=227
# @@protoc_insertion_point(module_scope)
